//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduBrilliant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaksi
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int KelasID { get; set; }
        public Nullable<System.DateTime> DateActivated { get; set; }
        public string Token { get; set; }
        public int IsActive { get; set; }
    
        public virtual Kela Kela { get; set; }
        public virtual User User { get; set; }
    }
}
